name: DriftBottle
version: ${project.version}
main: com.github.evanluo42.DriftBottle
api-version: 1.15
commands:
  db:
    description: DriftBottle's main command.
    usage: /db <throw/receive> [content]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>