name: DriftBottle
version: ${project.version}
main: com.github.evanluo42.DriftBottle
api-version: 1.15
commands:
  db:
    description: This is a demo command.
    usage: /<command> [player]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>